spring.datasource.url=jdbc:postgresql://dpg-da4t62e1egvs73a79sj0-a.oregon-postgres.render.com/moneymanager1_w7mq
spring.datasource.username=moneymanager1_w7mq_user
spring.datasource.password=ewkfy8DuiELXoHeroclVeCLaK8P7aQP5

